#!/usr/bin/env python3
"""notes/26 -- notes/19's clustering gate, on rules written by someone else.

notes/19 predicted which hidden rules a four-shot interface can learn, from class
separation alone, with the predictions frozen to disk first. It scored 12 of 14.
Its one obvious weakness is that Skye wrote all fourteen rules, so the set and the
hypothesis share an author.

These fourteen were generated by a different model through the Codex CLI, in a
read-only sandbox with the user's global instruction files excluded, from a prompt
that never mentions clustering, separation or learnability. The author is blind to
what is being tested. The prompt is saved next to the protocol.

**Thresholds are imported from ``run_clustering_prediction``, not restated**, so
this is an out-of-sample test of an already-registered rule rather than a new fit.
Same model, same layers, same design, same scoring.

    uv run python scripts/run_clustering_replication.py --phase measure
    uv run python scripts/run_clustering_replication.py --phase test

Phase ``test`` refuses to run before ``measure`` has frozen its predictions.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import time
from pathlib import Path
from typing import Any

import torch
from run_cluster_check import LAYERS, embed, separation
from run_clustering_prediction import (
    ACCURACY_THRESHOLD,
    SEPARATION_THRESHOLD,
    _fold,
)
from run_visible_rule_screen import (
    ANSWER_PREFIX,
    LABELS,
    MODEL,
    MODEL_REVISION,
    cells,
    render,
    score,
    twin_pair,
)

from introspect import models
from introspect.preflight import check as preflight_check

PROTOCOL = Path("results/clustering_replication_protocol_v1.json")
OUT = Path("results/clustering_replication_v1_raw.jsonl")
PROMPT = Path("results/clustering_replication_rule_prompt.txt")

#: Provenance of the rule set. Recorded so the blindness claim is checkable.
RULE_SOURCE = {
    "tool": "codex-cli 0.146.0",
    "invocation": (
        "codex exec --ignore-user-config --ignore-rules -s read-only "
        "--skip-git-repo-check -c project_doc_max_bytes=0"
    ),
    "reasoning_effort": "none",
    "session_id": "019ff82e-d08b-7660-90c4-dcda20840fcd",
    "generated_at": "2026-08-12",
    "author_blind_to_hypothesis": True,
    "prompt_file": str(PROMPT),
    "verified_by": (
        "All 14 distinctions checked for correctness by hand before any "
        "measurement. Correctness only -- not whether they would pass."
    ),
}

#: Exactly as returned, in the order returned. Not reordered, not filtered.
RULES: dict[str, tuple[list[str], list[str]]] = {
    "reptile_vs_amphibian": (["snake", "lizard", "turtle"], ["frog", "toad", "salamander"]),
    "flightless_vs_flying_bird": (
        ["ostrich", "penguin", "emu"],
        ["eagle", "sparrow", "albatross"],
    ),
    "renewable_vs_fossil_source": (
        ["sunlight", "wind", "geothermal"],
        ["coal", "petroleum", "gas"],
    ),
    "spelling_palindrome": (["level", "radar", "civic"], ["tiger", "melon", "cabin"]),
    "all_vowels_present": (
        ["education", "sequoia", "automobile"],
        ["rhythm", "blanket", "crisp"],
    ),
    "alphabetical_letters": (["almost", "biopsy", "chintz"], ["table", "zebra", "cloud"]),
    "comparative_vs_superlative": (
        ["larger", "smaller", "brighter"],
        ["largest", "smallest", "brightest"],
    ),
    "nominative_vs_accusative": (["I", "she", "they"], ["me", "her", "them"]),
    "regular_vs_irregular_past": (
        ["walked", "laughed", "painted"],
        ["went", "spoke", "wrote"],
    ),
    "even_vs_odd": (["14", "28", "62"], ["15", "31", "77"]),
    "perfect_square": (["16", "25", "49"], ["18", "26", "50"]),
    "fibonacci_number": (["13", "21", "34"], ["14", "22", "35"]),
    "silent_initial": (["knife", "gnome", "wrist"], ["nectar", "garden", "winter"]),
    "stress_position": (["paper", "window", "candle"], ["guitar", "hotel", "balloon"]),
}

#: Rules whose items are bare numerals. notes/19 called these "expressions" rather
#: than "items" in the prompt, and the same treatment is carried over so the two
#: runs differ only in the rules themselves.
NUMERIC = {"even_vs_odd", "perfect_square", "fibonacci_number"}

#: The rule names notes/19 used. Overlap here would make this a partial rerun
#: rather than a replication, so it is asserted rather than assumed.
NOTES_19_RULES = frozenset(
    {
        "colour_temp",
        "body_vs_furniture",
        "liquid_vs_solid",
        "vehicle_vs_plant",
        "sentiment",
        "letter_count",
        "ends_in_e",
        "double_letter",
        "multiple_of_three",
        "prime",
        "abstract_vs_concrete",
        "singular_vs_plural",
        "past_vs_present",
        "latin_vs_germanic",
    }
)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _spearman(xs: list[float], ys: list[float]) -> float:
    """Rank agreement, the pre-committed primary metric. Ties averaged."""

    def ranks(vs: list[float]) -> list[float]:
        order = sorted(range(len(vs)), key=lambda i: vs[i])
        out = [0.0] * len(vs)
        i = 0
        while i < len(order):
            j = i
            while j + 1 < len(order) and vs[order[j + 1]] == vs[order[i]]:
                j += 1
            shared = (i + j) / 2 + 1
            for k in range(i, j + 1):
                out[order[k]] = shared
            i = j + 1
        return out

    rx, ry = ranks(xs), ranks(ys)
    n = len(xs)
    mx, my = sum(rx) / n, sum(ry) / n
    num = sum((a - mx) * (b - my) for a, b in zip(rx, ry, strict=True))
    dx = sum((a - mx) ** 2 for a in rx) ** 0.5
    dy = sum((b - my) ** 2 for b in ry) ** 0.5
    return num / (dx * dy) if dx and dy else float("nan")


def _self_check() -> None:
    assert len(RULES) == 14, "notes/19 used fourteen; this must match"
    assert not (set(RULES) & NOTES_19_RULES), "a rule name is reused from notes/19"
    assert NUMERIC <= set(RULES), "NUMERIC names a rule that does not exist"
    for name, (a, b) in RULES.items():
        assert len(a) == len(b) == 3, f"{name}: three words per class"
        assert not (set(a) & set(b)), f"{name}: a word is in both classes"
    assert abs(SEPARATION_THRESHOLD - 0.020) < 1e-12, "threshold moved"
    assert abs(ACCURACY_THRESHOLD - 0.60) < 1e-12, "threshold moved"
    assert abs(_spearman([1, 2, 3, 4], [1, 2, 3, 4]) - 1.0) < 1e-9
    assert abs(_spearman([1, 2, 3, 4], [4, 3, 2, 1]) + 1.0) < 1e-9
    # Ties must average, not error: an all-equal column has no rank information.
    assert _spearman([1, 2, 3, 4], [1, 1, 1, 1]) != _spearman([1, 2, 3, 4], [1, 2, 3, 4])


def measure(args: argparse.Namespace) -> None:
    _self_check()
    if PROTOCOL.exists():
        raise SystemExit(f"protocol already frozen: {PROTOCOL}. Delete it only deliberately.")
    if not PROMPT.exists():
        raise SystemExit(f"missing rule-generation prompt at {PROMPT}; provenance is not optional")
    preflight_check(MODEL, training=False)
    model = models.load(MODEL, device=torch.device("mps"), revision=MODEL_REVISION)
    try:
        model.model.to(torch.bfloat16)
        object.__setattr__(model, "dtype", torch.bfloat16)

        predictions = {}
        for rule, (class_a, class_b) in RULES.items():
            per_layer = {}
            for layer in LAYERS:
                a = [embed(model, w, layer) for w in class_a]
                b = [embed(model, w, layer) for w in class_b]
                per_layer[f"layer_{layer}"] = separation(a, b)
            mean_sep = sum(per_layer.values()) / len(per_layer)
            predictions[rule] = {
                **per_layer,
                "mean_separation": mean_sep,
                "predicted_learnable": mean_sep >= SEPARATION_THRESHOLD,
            }
            verdict = "LEARNABLE" if mean_sep >= SEPARATION_THRESHOLD else "not learnable"
            print(f"{rule:28} sep {mean_sep:+.4f}  -> {verdict}", flush=True)

        protocol = {
            "what_this_is": (
                "notes/26. Predictions of rule learnability from class separation "
                "alone, frozen before any accuracy was measured, on fourteen rules "
                "written by a model blind to the hypothesis. Replication of notes/19."
            ),
            "replicates": "results/clustering_prediction_protocol_v1.json",
            "model": MODEL,
            "model_revision": MODEL_REVISION,
            "layers": list(LAYERS),
            "separation_threshold": SEPARATION_THRESHOLD,
            "accuracy_threshold": ACCURACY_THRESHOLD,
            "thresholds_derived_from": (
                "notes/16 gaps, via notes/19. Imported from run_clustering_prediction, "
                "not restated here, so they cannot drift."
            ),
            "primary_metric": (
                "Spearman rank agreement between mean_separation and accuracy across "
                "all fourteen rules. Pre-committed in notes/26 before any accuracy "
                "existed, because the binary count depends on how the outcome classes "
                "happen to balance. notes/19's rank agreement was 0.785."
            ),
            "rule_source": RULE_SOURCE,
            "rule_prompt_sha256": _sha256(PROMPT),
            "n_rules": len(RULES),
            "n_predicted_learnable": sum(
                bool(v["predicted_learnable"]) for v in predictions.values()
            ),
            "predictions": predictions,
            "source_sha256": {"run_clustering_replication.py": _sha256(Path(__file__))},
            "frozen_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        }
        PROTOCOL.parent.mkdir(parents=True, exist_ok=True)
        PROTOCOL.write_text(json.dumps(protocol, indent=2, sort_keys=True) + "\n")
        print(
            f"\nfroze {PROTOCOL} — "
            f"{protocol['n_predicted_learnable']}/{len(RULES)} predicted learnable",
            flush=True,
        )
    finally:
        model.free()


def test(args: argparse.Namespace) -> None:
    _self_check()
    if not PROTOCOL.exists():
        raise SystemExit(
            f"no frozen protocol at {PROTOCOL}. Run --phase measure first; "
            "this phase must not be run before predictions exist."
        )
    protocol = json.loads(PROTOCOL.read_text())
    summary_path = OUT.with_name(OUT.stem.removesuffix("_raw") + "_summary.json")
    for path in (OUT, summary_path):
        if path.exists():
            raise SystemExit(f"refusing to overwrite existing artifact: {path}")

    preflight_check(MODEL, training=False)
    model = models.load(MODEL, device=torch.device("mps"), revision=MODEL_REVISION)
    started = time.time()
    try:
        model.model.to(torch.bfloat16)
        object.__setattr__(model, "dtype", torch.bfloat16)
        design = cells()[:2] if args.smoke else cells()
        rows: list[dict[str, object]] = []

        for rule, (class_a, class_b) in RULES.items():
            a, b, query_a, query_b = _fold(class_a, class_b)
            for order, map_id, query_class in design:
                label_a, label_b = LABELS[map_id], LABELS[1 - map_id]
                pool, used = {0: list(a), 1: list(b)}, {0: 0, 1: 0}
                demos = []
                for which in order:
                    demos.append((pool[which][used[which]], label_a if which == 0 else label_b))
                    used[which] += 1
                query = query_a if query_class == 0 else query_b
                correct = label_a if query_class == 0 else label_b
                prompt = model.chat(render(demos, query, rule in NUMERIC), ANSWER_PREFIX)
                rows.append(
                    {
                        "rule": rule,
                        "fold": 0,
                        "order": list(order),
                        "map": map_id,
                        "query_class": query_class,
                        **score(model, prompt, correct),
                    }
                )
            print(f"{rule}: done", flush=True)

        OUT.parent.mkdir(parents=True, exist_ok=True)
        with OUT.open("w") as fh:
            for row in rows:
                fh.write(json.dumps(row, sort_keys=True) + "\n")

        results: dict[str, Any] = {}
        hits = 0
        for rule in RULES:
            sub = [r for r in rows if r["rule"] == rule]
            acc = sum(bool(r["correct"]) for r in sub) / len(sub)
            predicted = bool(protocol["predictions"][rule]["predicted_learnable"])
            observed = acc >= ACCURACY_THRESHOLD
            hit = predicted == observed
            hits += hit
            results[rule] = {
                "mean_separation": protocol["predictions"][rule]["mean_separation"],
                "predicted_learnable": predicted,
                "accuracy": acc,
                "twin_pair": twin_pair(sub),
                "observed_learnable": observed,
                "prediction_correct": hit,
            }

        seps = [float(results[r]["mean_separation"]) for r in RULES]
        accs = [float(results[r]["accuracy"]) for r in RULES]
        n_learnable = sum(bool(results[r]["observed_learnable"]) for r in RULES)
        majority = max(n_learnable, len(RULES) - n_learnable)

        summary = {
            "what_this_is": (
                "notes/26. notes/19's frozen clustering gate, scored on fourteen "
                "rules written by a model blind to the hypothesis."
            ),
            "protocol": str(PROTOCOL),
            "protocol_sha256": _sha256(PROTOCOL),
            "model": MODEL,
            "smoke": bool(args.smoke),
            "separation_threshold": SEPARATION_THRESHOLD,
            "accuracy_threshold": ACCURACY_THRESHOLD,
            "primary_rank_agreement": _spearman(seps, accs),
            "notes_19_rank_agreement": 0.785,
            "n_rules": len(RULES),
            "n_correct_predictions": hits,
            "majority_class_baseline": majority,
            "n_observed_learnable": n_learnable,
            "positive_separation_learnable": sum(
                1
                for r in RULES
                if results[r]["predicted_learnable"] and results[r]["observed_learnable"]
            ),
            "n_positive_separation": sum(1 for r in RULES if results[r]["predicted_learnable"]),
            "by_rule": results,
            "misses": [r for r, v in results.items() if not v["prediction_correct"]],
            "elapsed_seconds": round(time.time() - started, 1),
        }
        summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
        print(json.dumps(summary, indent=2, sort_keys=True), flush=True)
        print(
            f"\nrank agreement {summary['primary_rank_agreement']:.3f} "
            f"(notes/19: 0.785).  Binary {hits}/{len(RULES)}, "
            f"majority-class baseline {majority}/{len(RULES)}.",
            flush=True,
        )
    finally:
        model.free()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--phase", choices=("measure", "test"), required=True)
    parser.add_argument("--smoke", action="store_true")
    args = parser.parse_args()
    (measure if args.phase == "measure" else test)(args)


if __name__ == "__main__":
    main()
